permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Art Exposé"
  description: |
    Where art meets entretainment in apparel.
  font_url: "https://fonts.googleapis.com/css?family=Alef|Meddon|Montserrat:300,400|Mr+Dafoe|Playfair+Display&display=swap"
  colors:
    background: "--color-secondary"
    accent: "--color-coral"
    patterns:
      brand.logos: "--color-purple"

      icons.icons.twitter: "orange"
      icons.icons.instagram: "orange"
      icons.icons.cart: "orange"
      icons.icons.facebook: "orange"

  rationales:
    typefaces.primary: |
      Montserrat was selected because it is a classic font-for classic creatures.
    typefaces.secondary: |
      Playfair is only to be used for main titles inside banner.
    typefaces.terciary: |
      Meddon is only to be used for h1
    colors.primary: |
      The primary colours represent the theme of the website
    colors.secondary: |
      The secondary colours are more sutle and peaceful.

  layouts:
    default: |
      The default layout should be used for almost every page, it includes the website primary header and footer.
