patterns:
  product-card:
    width: 400
    description: |
      Thre product card is used on the product listing page to display the Products
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
