title: "Cards"
description: |
  Cards should be used to display products.

patterns:
  product-card:
    width: 300
    description: |
      The product card is used on the product listing page to display the Products
    fields:
      - name: 'product'
        type: 'card'
        data:
          source: "site.products[0]"
          type: Product
