title: "Cards"
description: |
  Cards should be used to display products.

patterns:
  cards:
    width: 300
    description: |
      The card is used on the product listing page to display the Products
    fields:
      - name: 'data'
        type: 'object'
        data: 'product'
          source: "site.products[0]"
          type: Product

  product-card:
    width: 300
    description: |
      The product card is used on the product listing page to display the Products
    fields:
      - name: 'product'
        type: 'card'
        data: 'product'
          source: "site.products[0]"
          type: Product
